version: "3"
services:
  producer:
    image: producer-app
    ports:
      - "8080:8080"
    networks:
      - consumer-producer
    environment:
      CONSUMER_URL_REST: http://consumer:8081/v1/api/random-numbers
      CONSUMER_URL_WEBSOCKET: ws://consumer:8081/v1/ws
      CSV_FILE_FOLDER: /temp/producer
      WEBSOCKET_USE: false

networks:
  consumer-producer: # Define the custom network
    external: true
